### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by ansarizafar** [holepunchto/rpc#13]
What is the status of this project? Is this project dead?

**Comment by kasperisager** [comment]
Not in the slightest! Why did you get the impression that it's dead?

**Comment by ansarizafar** [comment]
Last commit was 8 month ago. Is it possible to use this lib with Bunjs?

**Comment by mafintosh** [comment]
![](https://i.imgflip.com/95pocf.jpg)

**Comment by mafintosh** [comment]
@ansarizafar dont think it will, also depends heavily on libuv. runs on bare and node (and prop deno, but didnt try and no official support)

**Comment by kasperisager** [comment]
Bun uses `libuv`, but only on Windows, and Deno uses Tokio for asynchronous I/O, so neither will run our networking stack unfortunately.
